# Generated by Django 6.0.3 on 2026-03-28 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='fecha_asignacion',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora cuando el pedido fue asignado a un motorizado', null=True, verbose_name='Fecha de Asignación'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('pendiente_asignacion', 'Pendiente de Asignación'), ('confirmado', 'Confirmado'), ('en_preparacion', 'En Preparación'), ('en_camino', 'En Camino'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='pendiente_asignacion', max_length=20, verbose_name='Estado'),
        ),
    ]
