# Generated by Django 6.0.3 on 2026-03-27 02:28

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('cliente', 'Cliente'), ('motorizado', 'Motorizado'), ('admin', 'Administrador')], default='cliente', help_text='Rol del usuario en el sistema', max_length=20, verbose_name='Rol')),
                ('telefono', models.CharField(blank=True, help_text='Número de teléfono del usuario', max_length=15, verbose_name='Teléfono')),
                ('direccion', models.TextField(blank=True, help_text='Dirección principal del usuario', verbose_name='Dirección')),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='usuarios/perfiles/', verbose_name='Foto de Perfil')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['-fecha_registro'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='PerfilMotorizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa_vehiculo', models.CharField(help_text='Placa del vehículo del motorizado', max_length=10, verbose_name='Placa del Vehículo')),
                ('tipo_vehiculo', models.CharField(help_text='Ej: Moto, Bicicleta, Auto', max_length=50, verbose_name='Tipo de Vehículo')),
                ('licencia', models.CharField(help_text='Número de licencia de conducir', max_length=20, verbose_name='Número de Licencia')),
                ('disponible', models.BooleanField(default=True, help_text='Indica si el motorizado está disponible para entregas', verbose_name='Disponible')),
                ('calificacion', models.DecimalField(decimal_places=2, default=5.0, help_text='Calificación promedio del motorizado', max_digits=3, verbose_name='Calificación')),
                ('entregas_completadas', models.PositiveIntegerField(default=0, verbose_name='Entregas Completadas')),
                ('usuario', models.OneToOneField(limit_choices_to={'role': 'motorizado'}, on_delete=django.db.models.deletion.CASCADE, related_name='perfil_motorizado', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Motorizado',
                'verbose_name_plural': 'Perfiles de Motorizados',
            },
        ),
    ]
