# Generated by Django 6.0.3 on 2026-03-28 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilmotorizado',
            name='fecha_inicio_jornada',
            field=models.DateTimeField(blank=True, help_text='Cuándo inició la jornada actual', null=True, verbose_name='Fecha de Inicio de Jornada'),
        ),
        migrations.AddField(
            model_name='perfilmotorizado',
            name='jornada_activa',
            field=models.BooleanField(default=False, help_text='¿El motorizado tiene una jornada laboral activa?', verbose_name='Jornada Activa'),
        ),
        migrations.AddField(
            model_name='perfilmotorizado',
            name='ubicacion_actual',
            field=models.JSONField(blank=True, default=dict, help_text='Última ubicación conocida en formato {"lat": ..., "lng": ..., "timestamp": ...}', verbose_name='Ubicación Actual'),
        ),
    ]
