# Generated by Django 6.0.3 on 2026-03-27 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UbicacionTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitud', models.DecimalField(decimal_places=6, help_text='Coordenada de latitud GPS', max_digits=9, verbose_name='Latitud')),
                ('longitud', models.DecimalField(decimal_places=6, help_text='Coordenada de longitud GPS', max_digits=9, verbose_name='Longitud')),
                ('precision', models.FloatField(blank=True, help_text='Precisión en metros', null=True, verbose_name='Precisión')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora')),
            ],
            options={
                'verbose_name': 'Ubicación de Tracking',
                'verbose_name_plural': 'Ubicaciones de Tracking',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='RutaEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen_lat', models.DecimalField(decimal_places=6, help_text='Latitud de la tienda', max_digits=9, verbose_name='Latitud Origen')),
                ('origen_lng', models.DecimalField(decimal_places=6, help_text='Longitud de la tienda', max_digits=9, verbose_name='Longitud Origen')),
                ('destino_lat', models.DecimalField(decimal_places=6, help_text='Latitud del cliente', max_digits=9, verbose_name='Latitud Destino')),
                ('destino_lng', models.DecimalField(decimal_places=6, help_text='Longitud del cliente', max_digits=9, verbose_name='Longitud Destino')),
                ('distancia_km', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Distancia (km)')),
                ('tiempo_estimado_min', models.PositiveIntegerField(blank=True, null=True, verbose_name='Tiempo Estimado (minutos)')),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Inicio')),
                ('fecha_finalizacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Finalización')),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ruta', to='orders.pedido', verbose_name='Pedido')),
            ],
            options={
                'verbose_name': 'Ruta de Entrega',
                'verbose_name_plural': 'Rutas de Entregas',
            },
        ),
    ]
