# Generated by Django 6.0.3 on 2026-03-27 02:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_initial'),
        ('tracking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ubicaciontracking',
            name='motorizado',
            field=models.ForeignKey(limit_choices_to={'role': 'motorizado'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Motorizado'),
        ),
        migrations.AddField(
            model_name='ubicaciontracking',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ubicaciones', to='orders.pedido', verbose_name='Pedido'),
        ),
        migrations.AddIndex(
            model_name='ubicaciontracking',
            index=models.Index(fields=['pedido', '-timestamp'], name='tracking_ub_pedido__1e9c75_idx'),
        ),
    ]
